name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: docker
        tag_prefix: "v"
        root: "/"
        commit_message_template: "({{sha}} by {{author}}) {{message}}"
        version: "${{ steps.previous_step.outputs.version }}"